alter table UNIQCARS_ADDITIONAL_DATA add constraint FK_UNIQCARS_ADDITIONAL_DATA_ON_TYPE foreign key (TYPE_ID) references UNIQCARS_DIC_ADDITIONAL_TYPE(ID);
create index IDX_UNIQCARS_ADDITIONAL_DATA_ON_TYPE on UNIQCARS_ADDITIONAL_DATA (TYPE_ID);
