alter table UNIQCARS_ADDITIONAL_DATA add constraint FK_UNIQCARS_ADDITIONAL_DATA_ON_ITEM foreign key (ITEM_ID) references UNIQCARS_ITEM(ID);
create index IDX_UNIQCARS_ADDITIONAL_DATA_ON_ITEM on UNIQCARS_ADDITIONAL_DATA (ITEM_ID);
