-- begin UNIQCARS_BANK_CARD
alter table UNIQCARS_BANK_CARD add constraint FK_UNIQCARS_BANK_CARD_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_UNIQCARS_BANK_CARD_ON_USER on UNIQCARS_BANK_CARD (USER_ID)^
-- end UNIQCARS_BANK_CARD
-- begin UNIQCARS_ITEM
alter table UNIQCARS_ITEM add constraint FK_UNIQCARS_ITEM_ON_ITEM_TYPE foreign key (ITEM_TYPE_ID) references UNIQCARS_DIC_ITEM_TYPE(ID)^
create index IDX_UNIQCARS_ITEM_ON_ITEM_TYPE on UNIQCARS_ITEM (ITEM_TYPE_ID)^
-- end UNIQCARS_ITEM
-- begin UNIQCARS_ADDITIONAL_DATA
alter table UNIQCARS_ADDITIONAL_DATA add constraint FK_UNIQCARS_ADDITIONAL_DATA_ON_TYPE foreign key (TYPE_ID) references UNIQCARS_DIC_ADDITIONAL_TYPE(ID)^
alter table UNIQCARS_ADDITIONAL_DATA add constraint FK_UNIQCARS_ADDITIONAL_DATA_ON_ITEM foreign key (ITEM_ID) references UNIQCARS_ITEM(ID)^
alter table UNIQCARS_ADDITIONAL_DATA add constraint FK_UNIQCARS_ADDITIONAL_DATA_ON_CAR foreign key (CAR_ID) references UNIQCARS_CAR(ID)^
create index IDX_UNIQCARS_ADDITIONAL_DATA_ON_TYPE on UNIQCARS_ADDITIONAL_DATA (TYPE_ID)^
create index IDX_UNIQCARS_ADDITIONAL_DATA_ON_ITEM on UNIQCARS_ADDITIONAL_DATA (ITEM_ID)^
create index IDX_UNIQCARS_ADDITIONAL_DATA_ON_CAR on UNIQCARS_ADDITIONAL_DATA (CAR_ID)^
-- end UNIQCARS_ADDITIONAL_DATA

-- begin UNIQCARS_ADDITIONAL_DATA_FILE_DESCRIPTOR_LINK
alter table UNIQCARS_ADDITIONAL_DATA_FILE_DESCRIPTOR_LINK add constraint FK_ADDDATFILDES_ON_ADDITIONAL_DATA foreign key (ADDITIONAL_DATA_ID) references UNIQCARS_ADDITIONAL_DATA(ID)^
alter table UNIQCARS_ADDITIONAL_DATA_FILE_DESCRIPTOR_LINK add constraint FK_ADDDATFILDES_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
-- end UNIQCARS_ADDITIONAL_DATA_FILE_DESCRIPTOR_LINK
-- begin UNIQCARS_ITEM_FILE_DESCRIPTOR_LINK
alter table UNIQCARS_ITEM_FILE_DESCRIPTOR_LINK add constraint FK_ITEFILDES_ON_ITEM foreign key (ITEM_ID) references UNIQCARS_ITEM(ID)^
alter table UNIQCARS_ITEM_FILE_DESCRIPTOR_LINK add constraint FK_ITEFILDES_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
-- end UNIQCARS_ITEM_FILE_DESCRIPTOR_LINK
-- begin UNIQCARS_CAR_FILE_DESCRIPTOR_LINK
alter table UNIQCARS_CAR_FILE_DESCRIPTOR_LINK add constraint FK_CARFILDES_ON_CAR foreign key (CAR_ID) references UNIQCARS_CAR(ID)^
alter table UNIQCARS_CAR_FILE_DESCRIPTOR_LINK add constraint FK_CARFILDES_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
-- end UNIQCARS_CAR_FILE_DESCRIPTOR_LINK
-- begin UNIQCARS_ORDER
alter table UNIQCARS_ORDER add constraint FK_UNIQCARS_ORDER_ON_USER_EXT foreign key (USER_EXT_ID) references SEC_USER(ID)^
alter table UNIQCARS_ORDER add constraint FK_UNIQCARS_ORDER_ON_BANK_CARD foreign key (BANK_CARD_ID) references UNIQCARS_BANK_CARD(ID)^
alter table UNIQCARS_ORDER add constraint FK_UNIQCARS_ORDER_ON_CAR foreign key (CAR_ID) references UNIQCARS_CAR(ID)^
create index IDX_UNIQCARS_ORDER_ON_USER_EXT on UNIQCARS_ORDER (USER_EXT_ID)^
create index IDX_UNIQCARS_ORDER_ON_BANK_CARD on UNIQCARS_ORDER (BANK_CARD_ID)^
create index IDX_UNIQCARS_ORDER_ON_CAR on UNIQCARS_ORDER (CAR_ID)^
-- end UNIQCARS_ORDER
-- begin UNIQCARS_ORDER_ITEM_LINK
alter table UNIQCARS_ORDER_ITEM_LINK add constraint FK_ORDITE_ON_ORDER foreign key (ORDER_ID) references UNIQCARS_ORDER(ID)^
alter table UNIQCARS_ORDER_ITEM_LINK add constraint FK_ORDITE_ON_ITEM foreign key (ITEM_ID) references UNIQCARS_ITEM(ID)^
-- end UNIQCARS_ORDER_ITEM_LINK
-- begin UNIQCARS_ORDER_CAR_LINK
alter table UNIQCARS_ORDER_CAR_LINK add constraint FK_ORDCAR_ON_ORDER foreign key (ORDER_ID) references UNIQCARS_ORDER(ID)^
alter table UNIQCARS_ORDER_CAR_LINK add constraint FK_ORDCAR_ON_CAR foreign key (CAR_ID) references UNIQCARS_CAR(ID)^
-- end UNIQCARS_ORDER_CAR_LINK
-- begin UNIQCARS_PARTNER
alter table UNIQCARS_PARTNER add constraint FK_UNIQCARS_PARTNER_ON_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID)^
create index IDX_UNIQCARS_PARTNER_ON_IMAGE on UNIQCARS_PARTNER (IMAGE_ID)^
-- end UNIQCARS_PARTNER
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID)^
create index IDX_SEC_USER_ON_IMAGE on SEC_USER (IMAGE_ID)^
-- end SEC_USER
-- begin UNIQCARS_MEDIA
alter table UNIQCARS_MEDIA add constraint FK_UNIQCARS_MEDIA_ON_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID)^
alter table UNIQCARS_MEDIA add constraint FK_UNIQCARS_MEDIA_ON_PARTNER foreign key (PARTNER_ID) references UNIQCARS_PARTNER(ID)^
create index IDX_UNIQCARS_MEDIA_ON_IMAGE on UNIQCARS_MEDIA (IMAGE_ID)^
create index IDX_UNIQCARS_MEDIA_ON_PARTNER on UNIQCARS_MEDIA (PARTNER_ID)^
-- end UNIQCARS_MEDIA
-- begin UNIQCARS_MODEL_RANGE
alter table UNIQCARS_MODEL_RANGE add constraint FK_UNIQCARS_MODEL_RANGE_ON_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID)^
alter table UNIQCARS_MODEL_RANGE add constraint FK_UNIQCARS_MODEL_RANGE_ON_PARTNER foreign key (PARTNER_ID) references UNIQCARS_PARTNER(ID)^
create index IDX_UNIQCARS_MODEL_RANGE_ON_IMAGE on UNIQCARS_MODEL_RANGE (IMAGE_ID)^
create index IDX_UNIQCARS_MODEL_RANGE_ON_PARTNER on UNIQCARS_MODEL_RANGE (PARTNER_ID)^
-- end UNIQCARS_MODEL_RANGE
