-- begin UNIQCARS_ADDITIONAL_DATA
alter table UNIQCARS_ADDITIONAL_DATA add constraint FK_UNIQCARS_ADDITIONAL_DATA_ON_TYPE foreign key (TYPE_ID) references UNIQCARS_DIC_ADDITIONAL_TYPE(ID)^
alter table UNIQCARS_ADDITIONAL_DATA add constraint FK_UNIQCARS_ADDITIONAL_DATA_ON_ITEM foreign key (ITEM_ID) references UNIQCARS_ITEM(ID)^
create unique index IDX_UNIQCARS_ADDITIONAL_DATA_UNIQ_CODE on UNIQCARS_ADDITIONAL_DATA (CODE)^
create index IDX_UNIQCARS_ADDITIONAL_DATA_ON_TYPE on UNIQCARS_ADDITIONAL_DATA (TYPE_ID)^
create index IDX_UNIQCARS_ADDITIONAL_DATA_ON_ITEM on UNIQCARS_ADDITIONAL_DATA (ITEM_ID)^
-- end UNIQCARS_ADDITIONAL_DATA
-- begin UNIQCARS_ITEM
alter table UNIQCARS_ITEM add constraint FK_UNIQCARS_ITEM_ON_ITEM_TYPE foreign key (ITEM_TYPE_ID) references UNIQCARS_DIC_ITEM_TYPE(ID)^
create index IDX_UNIQCARS_ITEM_ON_ITEM_TYPE on UNIQCARS_ITEM (ITEM_TYPE_ID)^
-- end UNIQCARS_ITEM

-- begin UNIQCARS_ADDITIONAL_DATA_FILE_DESCRIPTOR_LINK
alter table UNIQCARS_ADDITIONAL_DATA_FILE_DESCRIPTOR_LINK add constraint FK_ADDDATFILDES_ON_ADDITIONAL_DATA foreign key (ADDITIONAL_DATA_ID) references UNIQCARS_ADDITIONAL_DATA(ID)^
alter table UNIQCARS_ADDITIONAL_DATA_FILE_DESCRIPTOR_LINK add constraint FK_ADDDATFILDES_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
-- end UNIQCARS_ADDITIONAL_DATA_FILE_DESCRIPTOR_LINK
-- begin UNIQCARS_ITEM_FILE_DESCRIPTOR_LINK
alter table UNIQCARS_ITEM_FILE_DESCRIPTOR_LINK add constraint FK_ITEFILDES_ON_ITEM foreign key (ITEM_ID) references UNIQCARS_ITEM(ID)^
alter table UNIQCARS_ITEM_FILE_DESCRIPTOR_LINK add constraint FK_ITEFILDES_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
-- end UNIQCARS_ITEM_FILE_DESCRIPTOR_LINK
-- begin UNIQCARS_DIC_ADDITIONAL_TYPE
create unique index IDX_UNIQCARS_DIC_ADDITIONAL_TYPE_UNIQ_CODE on UNIQCARS_DIC_ADDITIONAL_TYPE (CODE)^
-- end UNIQCARS_DIC_ADDITIONAL_TYPE
-- begin UNIQCARS_DIC_ITEM_TYPE
create unique index IDX_UNIQCARS_DIC_ITEM_TYPE_UNIQ_CODE on UNIQCARS_DIC_ITEM_TYPE (CODE)^
-- end UNIQCARS_DIC_ITEM_TYPE
-- begin UNIQCARS_BANK_CARD
alter table UNIQCARS_BANK_CARD add constraint FK_UNIQCARS_BANK_CARD_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_UNIQCARS_BANK_CARD_ON_USER on UNIQCARS_BANK_CARD (USER_ID)^
-- end UNIQCARS_BANK_CARD
-- begin UNIQCARS_ODER
alter table UNIQCARS_ODER add constraint FK_UNIQCARS_ODER_ON_ITEM foreign key (ITEM_ID) references UNIQCARS_ITEM(ID)^
create index IDX_UNIQCARS_ODER_ON_ITEM on UNIQCARS_ODER (ITEM_ID)^
-- end UNIQCARS_ODER
