alter table UNIQCARS_ADDITIONAL_DATA add constraint FK_UNIQCARS_ADDITIONAL_DATA_ON_TYPE foreign key (TYPE_ID) references UNIQCARS_DIC_ADDITIONAL_TYPE(ID);
alter table UNIQCARS_ADDITIONAL_DATA add constraint FK_UNIQCARS_ADDITIONAL_DATA_ON_ITEM foreign key (ITEM_ID) references UNIQCARS_ITEM(ID);
create unique index IDX_UNIQCARS_ADDITIONAL_DATA_UK_CODE on UNIQCARS_ADDITIONAL_DATA (CODE) where DELETE_TS is null ;
create index IDX_UNIQCARS_ADDITIONAL_DATA_ON_TYPE on UNIQCARS_ADDITIONAL_DATA (TYPE_ID);
create index IDX_UNIQCARS_ADDITIONAL_DATA_ON_ITEM on UNIQCARS_ADDITIONAL_DATA (ITEM_ID);
