alter table UNIQCARS_ADDITIONAL_DATA add constraint FK_UNIQCARS_ADDITIONAL_DATA_ON_CAR foreign key (CAR_ID) references UNIQCARS_CAR(ID);
create index IDX_UNIQCARS_ADDITIONAL_DATA_ON_CAR on UNIQCARS_ADDITIONAL_DATA (CAR_ID);
