alter table UNIQCARS_ITEM add constraint FK_UNIQCARS_ITEM_ON_ITEM_TYPE foreign key (ITEM_TYPE_ID) references UNIQCARS_DIC_ITEM_TYPE(ID);
create index IDX_UNIQCARS_ITEM_ON_ITEM_TYPE on UNIQCARS_ITEM (ITEM_TYPE_ID);
